title: Hayamizu lab
description: "Hayamizu lab: Treefit"
markdown: kramdown
highlighter: rouge
exclude:
  - ".dir-locals.el"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "vendor"

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: assets/stylesheets

defaults:
  - scope:
      path: "ja"
    values:
      path_prefix: /ja/
      layout: "base"
      language: ja
      country: JP
  - scope:
      path: ""
    values:
      path_prefix: /
      layout: "base"
      language: en
      country: US
